; ============================================================
; platformio.ini
; Configuración del proyecto PlatformIO para la Estación
; Ambiental IoT con ESP32.
;
; Placa : ESP32 DevKit V1 (30 pines, estándar del curso)
; Target: Compilación local y simulación en Wokwi.com
; ============================================================

[env:esp32dev]
platform   = espressif32
board      = esp32dev
framework  = arduino

; Velocidad del monitor serial (Coincide con SERIAL_BAUDRATE)
monitor_speed = 115200

; Fuerza a PlatformIO a buscar dependencias internas de las librerías
lib_ldf_mode = deep+

; Librerías del sensor DHT22 y comunicación HTTP
lib_deps =
    adafruit/DHT sensor library @ ^1.4.6
    adafruit/Adafruit Unified Sensor @ ^1.1.14
    bblanchon/ArduinoJson @ ^7.0.4

; Puerto serie para subir el código a la placa física
upload_port = COM9
